<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AtomUIDevelopTargetFramework);$(AtomUIProductionTargetFramework)</TargetFrameworks>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
        <RootNamespace>AtomUI.Controls</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
        <Compile Remove="Steps\Themes\StepsTheme.axaml\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Svg" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="AtomUI" />
        <InternalsVisibleTo Include="AtomUI.Controls.DataGrid" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../AtomUI.IconPkg.AntDesign/AtomUI.IconPkg.AntDesign.csproj" />
        <ProjectReference Include="../AtomUI.Theme/AtomUI.Theme.csproj" />
        <ProjectReference Include="../AtomUI.Generator/AtomUI.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaXaml Remove="Steps\Themes\StepsTheme.axaml\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="Steps\Themes\StepsTheme.axaml\**" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Remove="Steps\Themes\StepsTheme.axaml\**" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Remove="Steps\Themes\StepsTheme.axaml\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Steps\Themes\StepsTheme.axaml\**" />
    </ItemGroup>

</Project>
